// Orchestration Function: LightningIndexerPrologQuant
// Generated by PyPTO IR Compiler

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "pto_orchestration_api.h"

#define ARG_PTR_X 0
#define ARG_PTR_W_QB 1
#define ARG_PTR_W_QB_SCALE 2
#define ARG_PTR_WK 3
#define ARG_PTR_LN_GAMMA_K 4
#define ARG_PTR_LN_BETA_K 5
#define ARG_PTR_W_PROJ 6
#define ARG_PTR_COS 7
#define ARG_PTR_SIN 8
#define ARG_PTR_HADAMARD_Q 9
#define ARG_PTR_HADAMARD_K 10
#define ARG_PTR_Q_INT8_OUT 11
#define ARG_PTR_Q_SCALE_OUT 12
#define ARG_PTR_K_INT8_OUT 13
#define ARG_PTR_K_SCALE_OUT 14
#define ARG_PTR_WEIGHTS_OUT 15
#define ARG_PTR_WEIGHTS_NORM 16

// Helper to encode float as uint64_t for scalar params
static uint64_t float_to_u64(float f) {
    union {
        float f32;
        uint64_t u64;
    } conv;
    conv.u64 = 0;  // Clear upper bits
    conv.f32 = f;
    return conv.u64;
}

extern "C" {

__attribute__((visibility("default")))
PTO2OrchestrationConfig aicpu_orchestration_config(uint64_t* args, int arg_count) {
    (void)args;
    (void)arg_count;
    return PTO2OrchestrationConfig{
        .expected_arg_count = 17,
    };
}

__attribute__((visibility("default")))
void aicpu_orchestration_entry(PTO2Runtime* rt, uint64_t* args, int arg_count) {
    (void)arg_count;

    // Extract device pointers
    void* arg_x_ptr = reinterpret_cast<void*>(args[ARG_PTR_X]);
    void* arg_w_qb_ptr = reinterpret_cast<void*>(args[ARG_PTR_W_QB]);
    void* arg_w_qb_scale_ptr = reinterpret_cast<void*>(args[ARG_PTR_W_QB_SCALE]);
    void* arg_wk_ptr = reinterpret_cast<void*>(args[ARG_PTR_WK]);
    void* arg_ln_gamma_k_ptr = reinterpret_cast<void*>(args[ARG_PTR_LN_GAMMA_K]);
    void* arg_ln_beta_k_ptr = reinterpret_cast<void*>(args[ARG_PTR_LN_BETA_K]);
    void* arg_w_proj_ptr = reinterpret_cast<void*>(args[ARG_PTR_W_PROJ]);
    void* arg_cos_ptr = reinterpret_cast<void*>(args[ARG_PTR_COS]);
    void* arg_sin_ptr = reinterpret_cast<void*>(args[ARG_PTR_SIN]);
    void* arg_hadamard_q_ptr = reinterpret_cast<void*>(args[ARG_PTR_HADAMARD_Q]);
    void* arg_hadamard_k_ptr = reinterpret_cast<void*>(args[ARG_PTR_HADAMARD_K]);
    void* arg_q_int8_out_ptr = reinterpret_cast<void*>(args[ARG_PTR_Q_INT8_OUT]);
    void* arg_q_scale_out_ptr = reinterpret_cast<void*>(args[ARG_PTR_Q_SCALE_OUT]);
    void* arg_k_int8_out_ptr = reinterpret_cast<void*>(args[ARG_PTR_K_INT8_OUT]);
    void* arg_k_scale_out_ptr = reinterpret_cast<void*>(args[ARG_PTR_K_SCALE_OUT]);
    void* arg_weights_out_ptr = reinterpret_cast<void*>(args[ARG_PTR_WEIGHTS_OUT]);
    void* arg_weights_norm_ptr = reinterpret_cast<void*>(args[ARG_PTR_WEIGHTS_NORM]);

    // External tensors
    uint64_t x_shapes[2] = {192, 128};
    Tensor ext_x = make_tensor_external(arg_x_ptr, x_shapes, 2, DataType::FLOAT32);
    uint64_t w_qb_shapes[2] = {128, 64};
    Tensor ext_w_qb = make_tensor_external(arg_w_qb_ptr, w_qb_shapes, 2, DataType::FLOAT32);
    uint64_t w_qb_scale_shapes[2] = {192, 64};
    Tensor ext_w_qb_scale = make_tensor_external(arg_w_qb_scale_ptr, w_qb_scale_shapes, 2, DataType::FLOAT32);
    uint64_t wk_shapes[2] = {128, 64};
    Tensor ext_wk = make_tensor_external(arg_wk_ptr, wk_shapes, 2, DataType::FLOAT32);
    uint64_t ln_gamma_k_shapes[2] = {1, 64};
    Tensor ext_ln_gamma_k = make_tensor_external(arg_ln_gamma_k_ptr, ln_gamma_k_shapes, 2, DataType::FLOAT32);
    uint64_t ln_beta_k_shapes[2] = {1, 64};
    Tensor ext_ln_beta_k = make_tensor_external(arg_ln_beta_k_ptr, ln_beta_k_shapes, 2, DataType::FLOAT32);
    uint64_t w_proj_shapes[2] = {128, 64};
    Tensor ext_w_proj = make_tensor_external(arg_w_proj_ptr, w_proj_shapes, 2, DataType::FLOAT32);
    uint64_t cos_shapes[2] = {192, 64};
    Tensor ext_cos = make_tensor_external(arg_cos_ptr, cos_shapes, 2, DataType::FLOAT32);
    uint64_t sin_shapes[2] = {192, 64};
    Tensor ext_sin = make_tensor_external(arg_sin_ptr, sin_shapes, 2, DataType::FLOAT32);
    uint64_t hadamard_q_shapes[2] = {64, 64};
    Tensor ext_hadamard_q = make_tensor_external(arg_hadamard_q_ptr, hadamard_q_shapes, 2, DataType::FLOAT32);
    uint64_t hadamard_k_shapes[2] = {64, 64};
    Tensor ext_hadamard_k = make_tensor_external(arg_hadamard_k_ptr, hadamard_k_shapes, 2, DataType::FLOAT32);
    uint64_t q_int8_out_shapes[2] = {192, 64};
    Tensor ext_q_int8_out = make_tensor_external(arg_q_int8_out_ptr, q_int8_out_shapes, 2, DataType::INT8);
    uint64_t q_scale_out_shapes[2] = {192, 64};
    Tensor ext_q_scale_out = make_tensor_external(arg_q_scale_out_ptr, q_scale_out_shapes, 2, DataType::FLOAT32);
    uint64_t k_int8_out_shapes[2] = {192, 64};
    Tensor ext_k_int8_out = make_tensor_external(arg_k_int8_out_ptr, k_int8_out_shapes, 2, DataType::INT8);
    uint64_t k_scale_out_shapes[2] = {192, 64};
    Tensor ext_k_scale_out = make_tensor_external(arg_k_scale_out_ptr, k_scale_out_shapes, 2, DataType::FLOAT32);
    uint64_t weights_out_shapes[2] = {192, 64};
    Tensor ext_weights_out = make_tensor_external(arg_weights_out_ptr, weights_out_shapes, 2, DataType::FLOAT32);
    uint64_t weights_norm_shapes[2] = {192, 64};
    Tensor ext_weights_norm = make_tensor_external(arg_weights_norm_ptr, weights_norm_shapes, 2, DataType::FLOAT32);

    uint64_t q_raw_shapes[2] = {192, 64};
    Tensor q_raw = make_tensor(q_raw_shapes, 2, DataType::FLOAT32);
    uint64_t q_deq_shapes[2] = {192, 64};
    Tensor q_deq = make_tensor(q_deq_shapes, 2, DataType::FLOAT32);
    uint64_t q_roped_shapes[2] = {192, 64};
    Tensor q_roped = make_tensor(q_roped_shapes, 2, DataType::FLOAT32);
    uint64_t q_had_shapes[2] = {192, 64};
    Tensor q_had = make_tensor(q_had_shapes, 2, DataType::FLOAT32);
    uint64_t k_raw_shapes[2] = {192, 64};
    Tensor k_raw = make_tensor(k_raw_shapes, 2, DataType::FLOAT32);
    uint64_t k_normed_shapes[2] = {192, 64};
    Tensor k_normed = make_tensor(k_normed_shapes, 2, DataType::FLOAT32);
    uint64_t k_roped_shapes[2] = {192, 64};
    Tensor k_roped = make_tensor(k_roped_shapes, 2, DataType::FLOAT32);
    uint64_t k_had_shapes[2] = {192, 64};
    Tensor k_had = make_tensor(k_had_shapes, 2, DataType::FLOAT32);
    uint64_t weights_raw_shapes[2] = {192, 64};
    Tensor weights_raw = make_tensor(weights_raw_shapes, 2, DataType::FLOAT32);
    uint64_t tmp_shapes[2] = {192, 64};
    Tensor tmp = make_tensor(tmp_shapes, 2, DataType::FLOAT32);

    // Task 0: incore_matmul
    PTOParam params_t0[] = {
        make_input_param(ext_x),
        make_input_param(ext_w_qb),
        make_output_param(q_raw),
    };
    pto2_rt_submit_task(rt, 0, PTO2_WORKER_CUBE, params_t0, 3);

    // Task 1: incore_mul
    PTOParam params_t1[] = {
        make_input_param(q_raw),
        make_input_param(ext_w_qb_scale),
        make_output_param(q_deq),
    };
    pto2_rt_submit_task(rt, 1, PTO2_WORKER_VECTOR, params_t1, 3);

    // Task 2: incore_mul
    PTOParam params_t2[] = {
        make_input_param(q_deq),
        make_input_param(ext_cos),
        make_output_param(q_roped),
    };
    pto2_rt_submit_task(rt, 1, PTO2_WORKER_VECTOR, params_t2, 3);

    // Task 3: incore_matmul_nn
    PTOParam params_t3[] = {
        make_input_param(q_roped),
        make_input_param(ext_hadamard_q),
        make_output_param(q_had),
    };
    pto2_rt_submit_task(rt, 2, PTO2_WORKER_CUBE, params_t3, 3);

    // Task 4: incore_symmetric_quant
    PTOParam params_t4[] = {
        make_input_param(q_had),
        make_input_param(tmp),
        make_output_param(ext_q_int8_out),
        make_output_param(ext_q_scale_out),
    };
    pto2_rt_submit_task(rt, 3, PTO2_WORKER_VECTOR, params_t4, 4);

    // Task 5: incore_matmul
    PTOParam params_t5[] = {
        make_input_param(ext_x),
        make_input_param(ext_wk),
        make_output_param(k_raw),
    };
    pto2_rt_submit_task(rt, 0, PTO2_WORKER_CUBE, params_t5, 3);

    // Task 6: incore_layernorm
    PTOParam params_t6[] = {
        make_input_param(k_raw),
        make_input_param(ext_ln_gamma_k),
        make_input_param(ext_ln_beta_k),
        make_input_param(tmp),
        make_output_param(k_normed),
        make_scalar_param(float_to_u64(epsilon)),
    };
    pto2_rt_submit_task(rt, 4, PTO2_WORKER_VECTOR, params_t6, 6);

    // Task 7: incore_mul
    PTOParam params_t7[] = {
        make_input_param(k_normed),
        make_input_param(ext_cos),
        make_output_param(k_roped),
    };
    pto2_rt_submit_task(rt, 1, PTO2_WORKER_VECTOR, params_t7, 3);

    // Task 8: incore_matmul_nn
    PTOParam params_t8[] = {
        make_input_param(k_roped),
        make_input_param(ext_hadamard_k),
        make_output_param(k_had),
    };
    pto2_rt_submit_task(rt, 2, PTO2_WORKER_CUBE, params_t8, 3);

    // Task 9: incore_symmetric_quant
    PTOParam params_t9[] = {
        make_input_param(k_had),
        make_input_param(tmp),
        make_output_param(ext_k_int8_out),
        make_output_param(ext_k_scale_out),
    };
    pto2_rt_submit_task(rt, 3, PTO2_WORKER_VECTOR, params_t9, 4);

    // Task 10: incore_matmul
    PTOParam params_t10[] = {
        make_input_param(ext_x),
        make_input_param(ext_w_proj),
        make_output_param(weights_raw),
    };
    pto2_rt_submit_task(rt, 0, PTO2_WORKER_CUBE, params_t10, 3);

    // Task 11: incore_softmax
    PTOParam params_t11[] = {
        make_input_param(weights_raw),
        make_input_param(tmp),
        make_output_param(ext_weights_norm),
    };
    pto2_rt_submit_task(rt, 5, PTO2_WORKER_VECTOR, params_t11, 3);
}

}  // extern "C"
